version: "3"
services:
        openvpn-as:
                image: linuxserver/openvpn-as
                container_name: openvpn-as
                cap_add:
                        - NET_ADMIN
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/Denver
                ports:
                        - 943:943
                        - 9443:9443
                        - 1194:1194/udp
                volumes:
                        - ./config:/config
                restart: unless-stopped
